
spring:
  datasource:
    url: jdbc:mysql://rm-bp18jitlw9a952i5x3o.mysql.rds.aliyuncs.com:3306/vueadmin?userSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Kclkd2013

  redis:
    port: 6379
    host: 116.62.156.97
    database: 0
    password: kclkd2013


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
 #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



server:
  port: 8081
